name: "DDclient for Home Assistant"
version: "0.0.2"
slug: "ddclient"
description: "A dynamic DNS client for multiple providers"
arch:
  - "amd64"
  - "armv7"
  - "armhf"
  - "aarch64"
startup: "services"
boot: "auto"
options:
  ddclient_conf: "# Input your ddclient conf here"
schema:
  ddclient_conf: str
environment:
  DDCLIENT_CONF: "{options.ddclient_conf}"

